# docker-compose.yml (versión corregida)
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gym-app-api # Nombre actualizado
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:3000" # Mapea el puerto 5000 de tu PC al 3000 del contenedor
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: gym-app-client # Nombre actualizado
    ports:
      - "5173:5173" # Mapea el puerto 3000 de tu PC al 5173 del contenedor
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge