services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gym-app-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:3000"
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: gym-app-client
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge