services:
  # Servicio del Backend para Desarrollo
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gym-app-api-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:3000"
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modulescd.
      - ./uploads:/app/uploads

  # Servicio del Frontend para Desarrollo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Usa el Dockerfile de desarrollo
    container_name: gym-app-client-dev
    ports:
      - "5173:5173" # Vite corre en el puerto 5173
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge