# backend/Dockerfile.dev

# Usamos una imagen oficial de Node.js
FROM node:20-alpine

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos package.json y package-lock.json para instalar dependencias
# Docker guardará esta capa en caché, acelerando futuras construcciones
COPY package*.json ./

# Instalamos TODAS las dependencias (incluyendo las de desarrollo)
RUN npm install

# Exponemos el puerto por defecto de NestJS
EXPOSE 3000

# El comando para iniciar el servidor en modo de desarrollo
CMD ["npm", "run", "start:dev"]